resource_group_name = "lob-poc-one-rg"
resource_group_location = "East US"
subscription_id = " ${{secrets.azure_subscription_id}} "
tenant_id = " ${{secrets.azure_tenent_id}} "
client_id = " ${{secrets.user}} "
client_secret = " ${{secrets.password}} "
