name: RESOURCEGRUOP

on:
  push:
    branches: [ "git-actions" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false
    #container: 
      #image: kirankumarsivapuram/base_image:3.0             

    steps:
    - uses: actions/checkout@v3           
    - name: az login
      run: |
        az login --service-principal -u ${{secrets.user}} -p ${{secrets.password}} -t "5461eb53-e0fd-4320-92ff-c6efe1fe91e9"     
      
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan
    - name: Terraform Apply
      run: terraform apply -auto-approve
